language: android
jdk: oraclejdk8
os: linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
  - ./gradlew clean assemble test -a

notifications:
  email: false

