version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Gradle build
          command: ./gradlew clean assemble test
